var_dates:
  '2021-01-01':
  - B.1.1.7
  - B.1.351
  - P.1
  '2021-04-15':
  - B.1.1.7
  - B.1.351
  - P.1
  - B.1.617.2
  '2021-09-01':
  - B.1.617.2
  '2021-11-20':
  - B.1.617.2
  - BA.1
  - BA.2
  '2022-05-11':
  - BA.1
  - BA.2
  - BA.4
  - BA.5
  '2022-06-18':
  - BA.1
  - BA.2
  - BA.4
  - BA.5
  - BA.2.75
